### ISSUE TITLE
Different skin per wiki

### ISSUE THREAD

**Issue by ChiyoOsaka** [WikiMissing/mw-config#1]
WikiMissing skin is Monobook.
tech.wikimissing is Modern.

**Comment by nyuszika7h** [comment]
You should be able to do something like this, though I can't see `$wgSitename` defined in your `LocalSettings.php`:

```php
if ($wgSitename == 'WikiMissing Tech') {
  $wgDefaultSkin = 'modern';
} else {
  $wgDefaultSkin = 'monobook';
}
```

Note that most stuff only explicitly supports Vector and Monobook though, so you might have to work around some style bugs in `MediaWiki:modern.css`.

**Comment by nyuszika7h** [comment]
Or maybe you could use a preprocessor to have things specific to certain wikis in the global `LocalSettings.php` but only generate the actually relevant settings for that wiki.

**Comment by nyuszika7h** [comment]
Or maybe you could have site-specific settings in separate files and you'd `require()` the correct one with an `if`/`else`.

**Comment by nyuszika7h** [comment]
I just realized that the site name would have to be set in each wiki's `LocalSettings.php` explicitly so I'm not really sure how it would work.

**Comment by ChiyoOsaka** [comment]
Resolved a while ago.
