### ISSUE TITLE
CA issues

### ISSUE THREAD

**Issue by ChiyoOsaka** [WikiMissing/mw-config#19]
Even with `$wgCentralAuthAutoMigrate` as true, if `$wgGroupPermissions['*']['createaccount']` is false, a local account won't be created.

**Comment by nyuszika7h** [comment]
When I read CA I thought "certificate authority". :P

**Comment by ChiyoOsaka** [comment]
I know right? It's a bit confusing :P

Closing as it's a bit more complicated.
