### ISSUE TITLE
MySQL - deleting a user and it's access

### ISSUE THREAD

**Issue by ChiyoOsaka** [WikiMissing/mw-config#6]
If you delete a user, does it automatically remove the access the user had to databases?

**Comment by nyuszika7h** [comment]
Yes, it does.

> The **DROP USER** statement removes one or more MySQL accounts and their privileges. It removes privilege rows for the account from all grant tables.

http://dev.mysql.com/doc/refman/5.7/en/drop-user.html

**Comment by ChiyoOsaka** [comment]
Ah, cheers.
