### ISSUE TITLE
Find out how to add WikiMissing to interwiki

### ISSUE THREAD

**Issue by ChiyoOsaka** [WikiMissing/mw-config#7]
Find out how to add WikiMissing to Interwiki so other sites can use it too.

https://www.mediawiki.org/wiki/Extension:Interwiki

**Comment by nyuszika7h** [comment]
https://git.wikimedia.org/blob/mediawiki%2Fcore//maintenance%2Finterwiki.sql

**Comment by nyuszika7h** [comment]
https://www.mediawiki.org/wiki/Gerrit/Tutorial
